### PR TITLE
Added config option for overwriting database value

### PR DESCRIPTION
**Pull request by micahhenshaw**
Just asking if you would include an option to overwrite existing set timezones or not to.

### CODE REVIEW

**Comment by jamesmills** [comment]
Hi @micahhenshaw and thank you for your PR.

When would you intend to use this?

I assume you are wanting this so that if the user changes TimeZone (due to travelling or VPN) and the uses your application you don't want the system to update to use that new TimeZone. You want it to use the original TimeZone set when the user first signed in/up?

James

**Comment by micahhenshaw** [comment]
Hi @jamesmills 

There are a few cases that came to mind, your suggestion with the VPN is definitely one of them, also being on mobile data often results in IP address that don't necessarily reflect an accurate location (not sure how well geoip handles that). Also in cases where we could use your package to setup the timezone and use it for converting etc but give the user the option to manually select a timezone, in which case you wouldn't want to overwrite it.

Thanks,
Micah

**Comment by jamesmills** [comment]
I'm so sorry. I totally forgot about this.

We should add this for sure. Can you add something to the README file to explain this configuration options. Then I will merge it and add it to the CHANGELOG. 

Thank you!

**Comment by micahhenshaw** [comment]
Hi @jamesmills 

No problems! I have updated the README file

Thanks

**Pull request merged**
