### PR TITLE
Manage dependencies and add testing and lumen/laravel compatible

### PR DESCRIPTION
**Pull request by lloricode**

### CODE REVIEW

**Comment by lloricode** [comment]
to test the package run `composer i` then `vendor/bin/phpunit`

**Comment by lloricode** [comment]
@jamesmills can you check this?

**Comment by lloricode** [comment]
next is passport, is not necessary to include here, lets make an event so developer able to call this on their listener in project level

**Comment by lloricode** [comment]
currently im running test in `PHP 7.4` and `Laravel 7` so later i we need to make a github action so able to test all versions

**Comment by lloricode** [comment]
#29 need to revert, this must be done in project level

you can read this https://laravel.com/docs/7.x/passport#events

**Comment by lloricode** [comment]
maintainer did not response

**Comment by jamesmills** [comment]
Hi @lloricode sorry I didn't respond. I've struggled to keep onto of this package recently. I'll take a look at your PR soon. Thank you for your contribution and support.

**Pull request closed without merging**
