### PR TITLE
Added option to enable Carbon's translatedFormat 

### PR DESCRIPTION
**Pull request by aldesrahim**
Change format to translatedFormat for enabling translation.

Tested on Laravel 8

### CODE REVIEW

**Comment by aldesrahim** [comment]
translatedFormat used for localization output, basically it's return a translated date based on locale

**Comment by aldesrahim** [comment]
bump

**Comment by jamesmills** [comment]
My only issue with this is that it will force everything to use the `translatedFormat` when sometimes this might not be either expected or wanted.

I feel we need to add an option/flag or additional function for this.

Thoughts all?

**Comment by aldesrahim** [comment]
Hi @jamesmills, thanks for your response.

I've no problem if you want to add an option/flag or additional function for this, I agree to whatever path you're choosing 👍

**Comment by aldesrahim** [comment]
Hi @jamesmills, i've added some changes for enabling/toggling translation. if you have time, please take a look at my PR. Thank you !

**Pull request merged**
